version: 0.2
env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_USERS_SERVICE_URL: ${ALB_DNS}
    REACT_APP_SECRETME: "3oQ0f6EDD1Thi2lkF3xskKlH8mx07nHQ"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - env
      - env | grep $REACT_APP_USERS_SERVICE_URL
      - env | grep $REACT_APP_SECRETME
      - |
        if expr "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/main" >/dev/null  && expr "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/main" >/dev/null; then
          DOCKER_TAG=prod
        else
          DOCKER_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
        fi
      - echo "Docker tag:" $DOCKER_TAG
      - aws s3 cp s3://docker-token/.docker.key .docker.key
      - docker login -u reactnode32 --password-stdin < .docker.key
      - rm .docker.key
      - docker pull reactnode32/here-listen-users:$DOCKER_TAG || true
      - docker pull reactnode32/here-listen-client:builder || true
      - docker pull reactnode32/here-listen-client:$DOCKER_TAG || true
  build:
    commands:
      - echo building images
      - docker-compose up -d --build
      - echo Testing,Linting, should go here...
      - echo building prod images...
      - echo building User image  Builder image  Client image ...
      - echo Preparing to build Production! with DockerFile
      - >
        docker build \
          --cache-from reactnode32/here-listen-users:$DOCKER_TAG \
          -f users/Dockerfile \
          -t reactnode32/here-listen-users:$DOCKER_TAG \
          ./users
      - >
        docker build \
          --target builder \
          --cache-from reactnode32/here-listen-client:builder \
          -f client/Dockerfile \
          -t reactnode32/here-listen-client:builder \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL \
          ./client
      - >
        docker build \
          --cache-from reactnode32/here-listen-client:$DOCKER_TAG \
          -f client/Dockerfile \
          -t reactnode32/here-listen-client:$DOCKER_TAG \
          ./client
  post_build:
    commands:
      - echo pushing prod images to ecr..
      - docker push reactnode32/here-listen-users:$DOCKER_TAG
      - docker push reactnode32/here-listen-client:builder
      - docker push reactnode32/here-listen-client:$DOCKER_TAG
      - chmod +x ./deploy.sh
      - bash deploy.sh
