version: "3.7"
services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile.dev
    # command: ["/wait-for-it.sh", "users-db:3307", "--", "npm", "start"]
    volumes:
      - "./users:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      # Because it's in a different container we must use the container's IP
      # MYSQL_DATABASE: users_prod
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DATABASE_HOST: users-db #change this to users-db because it links to the other db container
    depends_on:
      - users-db
    restart: on-failure:5

  users-db:
    build:
      context: ./users/database
      dockerfile: Dockerfile
    environment:
      # MYSQL_DATABASE: users_prod
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      DATABASE_HOST: users-db #change this to users-db
    ports:
      - "3307:3306"
    # volumes:
    #   - users-db:/var/lib/mysql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users
volumes:
  users-db:
