version: "3.7"

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    volumes:
      - "./users:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      # Because it's in a different container we must use the container's IP
      MYSQL_DATABASE: users_prod
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DATABASE_HOST: SOME_DATABASE

    depends_on:
      - users-db
    restart: on-failure:5

  users-db:
    build:
      context: ./users/database
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: users_prod
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DATABASE_HOST: SOME_DATABASE
    ports:
      - "3307:3306"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        - REACT_APP_SECRETME=${REACT_APP_SECRETME}
    environment:
      - REACT_APP_SECRETME=${REACT_APP_SECRETME}
    ports:
      - 3007:80
    depends_on:
      - users
