version: 2

defaults: &defaults
  working_directory: ~/users
  docker:
    - image: circleci/node:8.9.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

workflows:
  version: 2
  only_test:
    jobs:
      - test
