version: 2
jobs:
  build:
    working_directory: ~/here-listen/
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          command: cd users && ls
      - run:
          command: cd users && npm install && npm test
