version: 2
jobs:
  build:
    working_directory: ~/here-listen/
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          command: pwd
      - run:
          command: cd users && npm install && npm test
