version: 2
#Implement some circleci?
defaults: &defaults
  working_directory: ~/../users
  docker:
    - image: circleci/node:8.9.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  only_test:
    jobs:
      - test
