version: 2
jobs:
  user:
    working_directory: ~/here-listen/
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          command: cd users && npm install && npm test
workflows:
  version: 2
  Test-User:
    jobs:
      - user
