version: 2
jobs:
  user:
    working_directory: ~/here-listen/
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          command: cd users && npm install && npm test
  client:
    working_directory: ~/here-listen/
    docker:
      - image: circleci/node:13
    steps:
      - checkout
workflows:
  version: 2
  Test-Servers:
    jobs:
      - user
  Test-Client:
    jobs:
      - client
